trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
- script: dotnet build RecipeAPISolution/src/RecipeAPI/RecipeApi.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'